#!/usr/bin/env python3
"""
Accuracy Calculation Module for DeGAML-LLM

This module computes accuracy from .jsonl result files generated by inference scripts.
Supports both multiple-choice questions (A/B/C/D) and boolean (True/False) tasks.

Extraction rules:
  - MCQ: Prefer FIRST occurrence of [A]/[B]/[C]/[D], fallback to FIRST standalone A/B/C/D
  - Bool: Prefer FIRST occurrence of [True]/[False], fallback to FIRST standalone True/False/T/F

Task type is auto-detected from labels or can be forced via command-line flag.

Usage:
    python -m degaml.core.accuracy /path/to/results.jsonl [--bool]
    
    Or programmatically:
    ```python
    from degaml.core.accuracy import compute_accuracy
    
    result = compute_accuracy("results.jsonl", task_type="auto")
    print(f"Accuracy: {result['accuracy']*100:.2f}%")
    ```
"""

import sys
import json
import re
from collections import defaultdict
from pathlib import Path
from typing import Dict, List, Optional, Tuple


# === Regular expressions for MCQ (A-D) ===
BRACKET_RE_MCQ = re.compile(r'\[([A-Da-d])\]')
STANDALONE_RE_MCQ = re.compile(r'(?<![A-Za-z0-9])([A-Da-d])(?![A-Za-z0-9])')

# === Regular expressions for Boolean (True/False) ===
BRACKET_RE_BOOL = re.compile(r'\[(True|False|T|F|true|false)\]', re.IGNORECASE)
STANDALONE_RE_BOOL = re.compile(
    r'(?<![A-Za-z0-9])((?:True|False|T|F|true|false))(?![A-Za-z0-9])', 
    re.IGNORECASE
)

# Helper mapping for single-letter T/F normalization
TF_MAP = {
    'T': 'True', 'F': 'False',
    't': 'True', 'f': 'False'
}


def detect_task_type_from_labels(labels_raw: List[str]) -> str:
    """Auto-detect task type ('mcq' or 'bool') from label strings.
    
    Args:
        labels_raw: List of raw label strings
        
    Returns:
        'mcq' or 'bool' based on majority matches
    """
    mcq_count = 0
    bool_count = 0
    
    for label in labels_raw:
        if not label:
            continue
        if BRACKET_RE_BOOL.search(label) or re.search(
            r'(?<![A-Za-z0-9])(True|False|T|F)(?![A-Za-z0-9])', 
            label, 
            re.IGNORECASE
        ):
            bool_count += 1
        if BRACKET_RE_MCQ.search(label) or STANDALONE_RE_MCQ.search(label):
            mcq_count += 1
    
    # Majority-based decision (fallback to 'mcq' on tie)
    if mcq_count > bool_count:
        return 'mcq'
    if bool_count > mcq_count:
        return 'bool'
    return 'mcq'


def normalize_tf_token(token: Optional[str]) -> Optional[str]:
    """Normalize True/False token to standard format.
    
    Args:
        token: Raw token ('T', 'F', 'true', 'False', etc.)
        
    Returns:
        'True' or 'False' or None
    """
    if token is None:
        return None
    token = token.strip()
    if not token:
        return None
    if len(token) == 1 and token in TF_MAP:
        return TF_MAP[token]
    if token.lower() == 'true':
        return 'True'
    if token.lower() == 'false':
        return 'False'
    return None


# === MCQ extraction functions ===
def extract_label_mcq(label_str: str) -> Optional[str]:
    """Extract true label (A/B/C/D) using first-occurrence preference.
    
    Args:
        label_str: Raw label string
        
    Returns:
        'A', 'B', 'C', 'D', or None
    """
    if not label_str:
        return None
    # Prefer bracketed like [C]
    m = BRACKET_RE_MCQ.search(label_str)
    if m:
        return m.group(1).upper()
    # Fallback: first standalone A-D
    m = STANDALONE_RE_MCQ.search(label_str)
    if m:
        return m.group(1).upper()
    return None


def extract_predict_mcq(pred_str: str) -> Optional[str]:
    """Extract predicted A/B/C/D using first-occurrence preference.
    
    Args:
        pred_str: Raw prediction string
        
    Returns:
        'A', 'B', 'C', 'D', or None
    """
    if not pred_str:
        return None
    m = BRACKET_RE_MCQ.search(pred_str)
    if m:
        return m.group(1).upper()
    m = STANDALONE_RE_MCQ.search(pred_str)
    if m:
        return m.group(1).upper()
    return None


# === Boolean extraction functions ===
def extract_label_bool(label_str: str) -> Optional[str]:
    """Extract true label (True/False) using first-occurrence preference.
    
    Args:
        label_str: Raw label string
        
    Returns:
        'True', 'False', or None
    """
    if not label_str:
        return None
    m = BRACKET_RE_BOOL.search(label_str)
    if m:
        return normalize_tf_token(m.group(1))
    m = STANDALONE_RE_BOOL.search(label_str)
    if m:
        return normalize_tf_token(m.group(1))
    return None


def extract_predict_bool(pred_str: str) -> Optional[str]:
    """Extract predicted True/False using first-occurrence preference.
    
    Args:
        pred_str: Raw prediction string
        
    Returns:
        'True', 'False', or None
    """
    if not pred_str:
        return None
    m = BRACKET_RE_BOOL.search(pred_str)
    if m:
        return normalize_tf_token(m.group(1))
    m = STANDALONE_RE_BOOL.search(pred_str)
    if m:
        return normalize_tf_token(m.group(1))
    # Fallback: search for literal true/false substrings
    m2 = re.search(r'(true|false)', pred_str, re.IGNORECASE)
    if m2:
        return normalize_tf_token(m2.group(1))
    return None


# === Unified extraction (dispatch based on task type) ===
def extract_label(label_str: str, task_type: str = 'mcq') -> Optional[str]:
    """Extract true label based on task type.
    
    Args:
        label_str: Raw label string
        task_type: 'mcq' or 'bool'
        
    Returns:
        Extracted label or None
    """
    if task_type == 'bool':
        return extract_label_bool(label_str)
    return extract_label_mcq(label_str)


def extract_predict(pred_str: str, task_type: str = 'mcq') -> Optional[str]:
    """Extract predicted answer based on task type.
    
    Args:
        pred_str: Raw prediction string
        task_type: 'mcq' or 'bool'
        
    Returns:
        Extracted prediction or None
    """
    if task_type == 'bool':
        return extract_predict_bool(pred_str)
    return extract_predict_mcq(pred_str)


def compute_accuracy(
    path: str, 
    task_type: str = 'auto'
) -> Dict:
    """Compute accuracy from a .jsonl result file.
    
    Args:
        path: Path to .jsonl file (each line has "predict" and "label" keys)
        task_type: 'mcq', 'bool', or 'auto' to auto-detect
        
    Returns:
        Dictionary containing:
            - total: Total number of examples
            - correct: Number of correct predictions
            - accuracy: Accuracy as float (0.0 to 1.0)
            - missing_extractions: Number of cases where extraction failed
            - per_label: Per-label accuracy breakdown
            - mismatches: List of incorrect predictions
            - task_type: Determined task type
    """
    total = 0
    correct = 0
    missing = 0
    per_label = defaultdict(lambda: {"total": 0, "correct": 0})
    mismatches = []
    
    # First pass: collect labels for auto-detection
    if task_type == 'auto':
        labels_raw = []
        with open(path, 'r', encoding='utf-8') as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                try:
                    obj = json.loads(line)
                    label = obj.get("label", "")
                    if not isinstance(label, str):
                        label = str(label)
                    labels_raw.append(label)
                except json.JSONDecodeError:
                    continue
        task_type = detect_task_type_from_labels(labels_raw)
    
    # Second pass: compute accuracy
    with open(path, 'r', encoding='utf-8') as f:
        for idx, line in enumerate(f, start=1):
            line = line.strip()
            if not line:
                continue
            try:
                obj = json.loads(line)
            except json.JSONDecodeError:
                continue
            
            pred_raw = obj.get("predict", "")
            label_raw = obj.get("label", "")
            
            if not isinstance(pred_raw, str):
                pred_raw = str(pred_raw)
            if not isinstance(label_raw, str):
                label_raw = str(label_raw)
            
            true = extract_label(label_raw, task_type)
            pred = extract_predict(pred_raw, task_type)
            
            total += 1
            if true is None or pred is None:
                missing += 1
            
            is_correct = (true is not None and pred is not None and true == pred)
            if is_correct:
                correct += 1
            
            if true:
                per_label[true]["total"] += 1
                if is_correct:
                    per_label[true]["correct"] += 1
            
            if not is_correct:
                mismatches.append({
                    "idx": idx,
                    "true": true,
                    "pred": pred,
                    "label_snippet": label_raw[:200],
                    "pred_snippet": pred_raw[:200]
                })
    
    accuracy = (correct / total) if total else 0.0
    return {
        "total": total,
        "correct": correct,
        "accuracy": accuracy,
        "missing_extractions": missing,
        "per_label": dict(per_label),
        "mismatches": mismatches,
        "task_type": task_type
    }


def print_report(result: Dict, max_mismatches: int = 10):
    """Print a formatted accuracy report.
    
    Args:
        result: Result dictionary from compute_accuracy()
        max_mismatches: Maximum number of mismatches to display
    """
    task_type = result.get('task_type', 'mcq')
    print(f"Task type: {task_type}")
    print(f"Total examples: {result['total']}")
    print(f"Correct: {result['correct']}")
    print(f"Accuracy: {result['accuracy']*100:.2f}%")
    print(f"Cases with missing extraction: {result['missing_extractions']}\n")
    
    print("Per-label breakdown:")
    for label in sorted(result["per_label"].keys(), key=lambda x: str(x)):
        d = result["per_label"][label]
        acc = (d["correct"]/d["total"]) if d["total"] else 0.0
        print(f"  {label}: {d['correct']}/{d['total']} ({acc*100:.2f}%)")


def main():
    """Command-line interface for accuracy calculation."""
    if len(sys.argv) < 2:
        print("Usage: python -m degaml.core.accuracy <results.jsonl> [--bool]")
        print("  --bool  Force boolean (True/False) task type")
        print("  Without --bool, task type is auto-detected from labels")
        sys.exit(1)
    
    path = sys.argv[1]
    
    # Check for --bool flag
    task_type = 'auto'
    if '--bool' in sys.argv:
        task_type = 'bool'
    
    result = compute_accuracy(path, task_type)
    print_report(result)


if __name__ == "__main__":
    main()
